// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P2_AP1_Felix_20180570.DAL;

namespace P2_AP1_Felix_20180570.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20211108233649_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("P2_AP1_Felix_20180570.Entidades.Proyectos", b =>
                {
                    b.Property<int>("ProyectoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int>("TiempoTotal")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProyectoID");

                    b.ToTable("Proyectos");
                });

            modelBuilder.Entity("P2_AP1_Felix_20180570.Entidades.TareasDetalle", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProyectoID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Requerimiento")
                        .HasColumnType("TEXT");

                    b.Property<int>("Tiempo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoTareaID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("ProyectoID");

                    b.HasIndex("TipoTareaID");

                    b.ToTable("TareasDetalle");
                });

            modelBuilder.Entity("P2_AP1_Felix_20180570.Entidades.TiposTareas", b =>
                {
                    b.Property<int>("TipoTareaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoTarea")
                        .HasColumnType("TEXT");

                    b.HasKey("TipoTareaID");

                    b.ToTable("TiposTareas");

                    b.HasData(
                        new
                        {
                            TipoTareaID = 1,
                            TipoTarea = "Analisis"
                        },
                        new
                        {
                            TipoTareaID = 2,
                            TipoTarea = "Diseño"
                        },
                        new
                        {
                            TipoTareaID = 3,
                            TipoTarea = "Programacion"
                        },
                        new
                        {
                            TipoTareaID = 4,
                            TipoTarea = "Prueba"
                        });
                });

            modelBuilder.Entity("P2_AP1_Felix_20180570.Entidades.TareasDetalle", b =>
                {
                    b.HasOne("P2_AP1_Felix_20180570.Entidades.Proyectos", null)
                        .WithMany("DetalleTarea")
                        .HasForeignKey("ProyectoID");

                    b.HasOne("P2_AP1_Felix_20180570.Entidades.TiposTareas", "TipoTareas")
                        .WithMany()
                        .HasForeignKey("TipoTareaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoTareas");
                });

            modelBuilder.Entity("P2_AP1_Felix_20180570.Entidades.Proyectos", b =>
                {
                    b.Navigation("DetalleTarea");
                });
#pragma warning restore 612, 618
        }
    }
}
