// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P2_AP1_Felix_20180570.DAL;

namespace P2_AP1_Felix_20180570.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("P2_AP1_Felix_20180570.Entidades.TiposTareas", b =>
                {
                    b.Property<int>("TipoTareaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoTarea")
                        .HasColumnType("TEXT");

                    b.HasKey("TipoTareaID");

                    b.ToTable("TiposTareas");

                    b.HasData(
                        new
                        {
                            TipoTareaID = 1,
                            TipoTarea = "Analisis"
                        },
                        new
                        {
                            TipoTareaID = 2,
                            TipoTarea = "Diseño"
                        },
                        new
                        {
                            TipoTareaID = 3,
                            TipoTarea = "Programacion"
                        },
                        new
                        {
                            TipoTareaID = 4,
                            TipoTarea = "Prueba"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
